<?php

namespace AppBundle\Repository;

/**
 * LakeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LakeRepository extends \Doctrine\ORM\EntityRepository
{
}
